marcj/deepkit

- .github/workflows/main.yml
- packages/framework/src/application-server.ts
- packages/framework/src/cli/server-start.ts
- packages/framework/src/kernel.ts
- packages/framework/tests/application-server.spec.ts
Updates the ApplicationServer to determine if an HTTP worker is required based on whether or not the application specifies HTTP controllers/routes, RPC controllers or publicDir
Fixes #117 
> feat: conditionally start the http listener based on presence of routes, rpc and publicDir

- packages/api-console/main.ts
- packages/app/src/application.ts
- packages/app/src/configuration.ts
- packages/app/tests/application.spec.ts
- packages/app/tests/test.env
- Combines `loadConfigFromEnvFile` and `loadConfigFromEnvVariables` into a simpler unified API with sane defaults for `APP_` prefix and automatic loading of a root `.env` file if it is available
> feat: improvements to env config loading

- release-notes/alpha-53.md
- Updates code samples to reference `FrameworkModule` instead of `FrameworkBundle`
- Minor changes to make it read more naturally to english speakers
> docs: updates to alpha 53 release notes

- packages/rpc/src/server/action.ts
- packages/rpc/src/server/security.ts
- packages/rpc/tests/security.spec.ts
There should be a way to hide internal stack-traces which can contain confidential information, or needlessly helping hackers to figure out how the system is built
> Allow to process RPC errors, fixes #168

- packages/http/src/model.ts
- packages/http/src/router.ts
- packages/http/tests/router.spec.ts
- moved `formidable` initiatialization to be per request
- use `request.body` for raw form data access to allow more interoperability with connect middlewares and other software stacks. (note: I personally this need a way to access form data in early event handlers so this is an easy way for me to do it)
> Fix simultanous requests with form data, closes #166

- packages/type/src/model.ts
Fix for issue where child classes did not actually inherit methods of the base classes when using mixins. 
> Fix: Make mixin inherit methods

- packages/core/src/core.ts
- packages/type/src/model.ts
Fix for mixins not being able to inherit from abstract classes.
> Mixin inherit abstract

- packages/framework/src/testing.ts
feat(framework): replace `TestHttpResponse` with `MemoryHttpResponse`
> feat(framework): replace `TestHttpResponse` with `MemoryHttpResponse`

- packages/orm/src/plugin/soft-delete.ts
- packages/orm/src/query.ts
- packages/orm/tests/query.spec.ts
- `query.filter()` now appends to rather than replaces the previous filter conditions.
- `query.addField()` is replaced by `query.filterField()`
- `query.filterNone()` is added to clear filter conditions
BREAKING CHANGE
> feat(orm): redesign query filter methods

- packages/type/src/reflection/type.ts
- packages/type/tests/validation.spec.ts
Now checks function implementations when comparing whether the type of two functions is identical.
Fixes an issue reported by @pavel-voronin on the discord ([message link](https://discord.com/channels/759513055117180999/759513055607783478/1001093079840858162)):
```ts
function aValidation() {
console.log("aValidation");
}
function bValidation() {
console.log("bValidation");
}
class DTO {
a: string & Validate<typeof aValidation>;
b: string & Validate<typeof bValidation>;
}
export class TestController {
@http.POST("hello")
async hello(body: HttpBody<DTO>) {
return body;
}
}
new App({
controllers: [TestController],
imports: [new FrameworkModule()],
}).run();
```
```shell
curl --request POST \
--url http://localhost:8080/hello \
--header 'content-type: application/json' \
--data '{"a": …
```
> fix(type): added isSameType(function, function) strict comparison on function implementations

- packages/http/src/router.ts
- packages/http/tests/parameter-resolver.spec.ts
Provides resolvers with type information.  As an example case, this enables a resolver to determine optionality in order to understand if they should throw vs return `undefined` in the event they're unable to resolve a value.
> add type to RouteParameterResolverContext

- packages/sqlite/src/sqlite-adapter.ts
- packages/sqlite/tests/sqlite.spec.ts
Fixed an off-by-one error in the connection pool for sqlite, that causes one too many connections to be allowed to be created. This is especially problematic for SQLite :memory: databases, as having multiple connections to these is not possible. Instead, this will create two disjoint in-memory databases, which is problematic 
> fix(sqlite): fix off-by-one in max number of active connections

- packages/type/src/type-serialization.ts
Prefers using [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) to access the global object, which is standard across node and browser environments. I'm not sure what versions of browsers/node Deepkit is obligated to support, so we may be able to drop the `envGlobal` variable and just go with `globalThis` everywhere.
> Use cross-environment `globalThis` to access the global object.

- packages/create-app/files/app.ts
- packages/create-app/files/client.rpc.ts
- packages/create-app/files/package.json
- packages/create-app/files/src/controller/hello-world.cli.ts
- packages/create-app/files/src/controller/hello-world.http.ts
- packages/create-app/files/src/controller/hello-world.rpc.ts
- packages/create-app/files/tests/app.spec.ts
- packages/create-app/files/tests/cli.spec.ts
- packages/create-app/files/tests/http.spec.ts
- packages/create-app/files/tests/rpc.spec.ts
This change removes the .js extension for the files that will be created through `npm init @deepkit/app`
> fix(create-app): remove .js extension for the files being created

- packages/sql/src/sql-filter-builder.ts
- packages/sql/tests/sql-query.spec.ts
Fixes an issue where the SQL filter condition `{ fieldA: { $ne: null } }` yields `fieldA IS NULL` in the resulting SQL.
> fix SQL not null

- packages/injector/src/injector.ts
> fix(injector): add missing factoryDependencyNotFound function in resolver compiler context

- .github/workflows/main.yml
I noticed CI is still running Node 14 for ORM tests, and Node 16 for unit tests.  Node 14 has been EOL'ed, Node 18 is the current LTS, and Node 16 will be EOL'ed in 5 months.
This PR bumps everything to Node 18.
> bump Node to current LTS (18.x)

- packages/mysql/src/mysql-adapter.ts
- packages/mysql/tests/mysql.spec.ts
Without the added condition, executing a patch that has zero modified rows throws:
```
TypeError: Cannot read properties of null (reading 'map')
487 |             const returning = result[1][0];
> 488 |             patchResult.primaryKeys = (JSON.parse(returning['@_pk']) as any[]).map(primaryKeyConverted as any);
|                                                                                   ^
489 |
490 |             for (const i in aggregateFields) {
at MySQLQueryResolver.patch (src/mysql-adapter.ts:488:83)
at MySQLDatabaseQuery.patch (../orm/src/query.ts:859:17)
at MySQLDatabaseQuery.patchMany (../orm/src/query.ts:825:16)
at Object.<anonymous> (tests/mysql.spec.ts:207:24)
```
> mysql: fix patch PrimaryKey extraction when there were no modified rows

- packages/type/src/serializer.ts
- packages/type/tests/serializer.spec.ts
I have a use case where a client _may_ specify `"mechanism": "cookie"` as part of their payload.
The code looks like:
```
@http.POST()
login(body: HttpBody<{ ..., mechanism?: 'cookie' }>) {
// ...
}
```
I found that `mechanism` was _always_ set to `cookie`, even when the client didn't specify it.
I can work around it with a `mechanism?: 'cookie' | 'jwt'`, which is more representative of the actual intent -- but I figure it's probably supposed to work the way I originally expected anyway.
> fix default assignment for optional literals

- packages/api-console-gui/src/app/views/http/route-detail.component.ts
- packages/api-console-gui/src/app/views/overview.component.html
- packages/api-console-gui/src/app/views/view-styles.scss
show the route description with white-space:pre-wrap to respect the newlines the developer used in description for formatting
> debugger: show the route description with original formatting (newlines)

- packages/mongo/src/adapter.ts
- packages/mongo/src/client/command/createIndexes.ts
- packages/mongo/tests/mongo-index.spec.ts
- packages/type/src/reflection/type.ts
adds support for expireAfterSeconds index for mongodb
a jest test is provided BUT ...
I've no idea how to get the indexes out of db to compare.
At least you can manually look into the db to check the indexes and I can see that the indexes are created as intended.
A possible small bug I've found: look for "notIntendedAItSeemsOrBug"
> adds support for expireAfterSeconds index for mongodb

- .github/workflows/main.yml
- packages/type/src/reflection/type.ts
Fixes the failing `basic union with number | uuid` test in `bson` package
> fix(type): ensure both types have names before comparing in isSameType function

- packages/bson/index.ts
Fixes https://github.com/deepkit/deepkit-framework/issues/453#issuecomment-1618894690
> fix(bson): import named __ΩBSONDeserializer not found in module

- packages/type-compiler/src/compiler.ts
- packages/type/src/reflection/reflection.ts
- packages/type/src/reflection/type.ts
- packages/type/tests/jsdoc.spec.ts
Expands support for jsDoc @description info, on classes, methods, functions, enums, interfaces, and type aliases. This was needed for an unreleased project I'm working on.
Changes are in `type/src/reflection/` and `type-compiler/src/compiler.ts`.
Tests have been added in `packages/type/tests/jsdoc.spec.ts`.
Thanks to the Deepkit team for the amazing project!
> Make JSDoc @description tags available on more reflection classes and types

- packages/type-compiler/src/compiler.ts
Fixes https://github.com/deepkit/deepkit-framework/issues/455
Author @timvandam (https://discord.com/channels/759513055117180999/956485210676002816/1138433915221196912)
> fix(type-compiler): Node InferType did not pass test isEntityName

- packages/http/src/request-parser.ts
- packages/http/src/router.ts
- packages/http/tests/router.spec.ts
An API consumer is currently able to manually specify a JSON payload matching the shape of UploadedFile and Deepkit will accept it. This opens the application up to exploitation by bad actors providing payloads with sensitive paths.
While the developer could verify against the uploadedFiles property of HttpRequest to prevent against this manually, I believe this should be something the framework protects against, plus has the benefit of cleaner code in controllers.
This is an alternate implementation to #459, as #459 does not work when the HttpBody/HttpBodyValidation type argument is a complex type.  The `typeof UploadedFileSymbol | null` union resolves the issue described [here](https://github.com/deepkit/deepkit-framework/pull/459#issuecomment-1616574406).
My preference would have been …
> fix(http): prevent JSON payloads from spoofing UploadedFile

- README.md
> chore: add entries to community packages and examples

- packages/framework/src/module.ts
- packages/injector/src/injector.ts
- packages/injector/src/provider.ts
- packages/injector/tests/injector.spec.ts
- packages/logger/package.json
- packages/logger/src/logger.ts
- packages/logger/tests/logger.spec.ts
Adds a `TransientInjectorTarget` class that can be injected into transient providers/useFactory functions when the provider is injected into other providers. This allows for the creation of context aware classes, such as loggers scoped to the class they are used in.
Also adds a `ScopedLogger` to @deepkit/logger and @deepkit/framework's `FrameworkModule` that uses `TransientInjectorTarget` to create loggers scoped to the provider token name
> TransientInjectorTarget & ScopedLogger

- packages/app/src/module.ts
- packages/app/tests/module.spec.ts
Currently, it's only possible to export interface providers using `this.addExport(provider)` in modules. This aims to try to solve that by allowing `NormalizedProvider`s to be exported directly in `createModule`.
https://discord.com/channels/759513055117180999/956486106709364776/1089925501113614527
> feat(app): allow normalized providers to be exported in modules

- packages/injector/src/injector.ts
- packages/injector/tests/injector.spec.ts
Utility PartialFactory type that makes it easy to resolve providers when instantiating non-provider classes.
```ts
class A {
constructor (public readonly b: B, public readonly num: number) {
}
}
class B {
public b = 'b';
}
const injector = Injector.from([B]);
const factory = injector.get<PartialFactory<A>>();
const a = factory({
num: 5,
});
// A { B { b: 'b' }, num: 5 }
```
> feature(injector): PartialFactory

- packages/type-compiler/deepkit-type-install.js
Last release installation fails due to inability to install type compiler.
This PR adds required shebang
> Fix installation failure due to the lack of shebang.

- packages/type-compiler/src/compiler.ts
- packages/type-compiler/tests/transpile.spec.ts
#463 introduced a bug where compilation of certain inline types causes a crash of tsc due to `narrowed.parent` having an undefined value.
> Repair compilation of inline type definitions with generics

- packages/type/src/reflection/type.ts
- packages/type/tests/valuesof-union.spec.ts
This enables `valuesOf` to work on indexed unions and when the index into the union is also a union.
See the included tests for examples of functionality that now works (all of which did not previously work).
I hereby release these code changes under the MIT license but waive the requirement for name attribution, inclusion of copyright and/or permission notice.
> Extend `valuesOf` to work with unions

- package-lock.json
- packages/type-compiler/package.json
- packages/type-compiler/src/compiler.ts
- packages/type-compiler/tests/transpile.spec.ts
- packages/type-compiler/tests/utils.ts
> fix(type-compiler): set ts compiler options target to es2022 if esnext when resolving global lib files

- package-lock.json
- packages/type-compiler/src/compiler.ts
- packages/type/tests/compiler.spec.ts
Fixes https://github.com/deepkit/deepkit-framework/issues/454
> fix(type-compiler): arrow function receive type

- packages/mongo/src/persistence.ts
- packages/orm-integration/src/various.ts
- packages/sql/src/sql-adapter.ts
> feat(mongo,sql): skip database field for inserts

- packages/mysql/tests/mysql.spec.ts
- packages/sql/src/platform/default-platform.ts
The other typeResolvesToX functions filter out undefined/null before determining if the type correctly resolves, but string does not.  As a result, `string | null` types on database entities are being coerced to JSON.
> fix(sql): strings should be nullable without casting as JSON

- packages/injector/src/injector.ts
> feat(injector): improve set method api

- packages/mysql/src/mysql-platform.ts
- packages/mysql/tests/mysql.spec.ts
- packages/sql/src/platform/default-platform.ts
Same as #552, but for dates. Can't use `Date | null` on SQL entities right now without Deepkit trying to cast them as JSON into the database.
> fix(sql): dates should be nullable without casting as JSON

- packages/http/src/request-parser.ts
- packages/http/tests/router.spec.ts
JSON array payloads are converted into objects by formidable.  This prevents HttpBody/HttpBodyValidator from properly validating the data (it doesn't pass the `isIterable` check, so `body` ends up being `undefined` after serialization).
> fix(http): support for JSON array payloads

- packages/type/src/serializer.ts
- packages/type/tests/validation.spec.ts
Instead of just first as previously https://github.com/deepkit/deepkit-framework/issues/565#issuecomment-2091054710
I wasn't able to run the test suite on my machine so couldn't check if tests were passing after modifications.
As discussed https://discord.com/channels/759513055117180999/956485210676002816/1239901714832822302
> refactor(type): return all errors when validating array

- packages/bun/README.md
Users of Bun most likely want to use the "battery included" test runner instead of separately installing Jest.
For newcomers that want to use Bun it might not be obvious that root `preload` doesn't apply for tests also and they get the error `No valid runtime type ... given` when running the tests.
Show how to setup this plugin to be able to use the bun test runner.
> docs(bun): setup bun test runner

- .github/workflows/main.yml
- packages/sql/tests/sql-query.spec.ts
@deepkit/sql tests should have been failing since the addition of:
https://github.com/deepkit/deepkit-framework/blame/v1.0.1-alpha.153/packages/sql/src/sql-filter-builder.ts#L31
where the following wasn't updated:
https://github.com/deepkit/deepkit-framework/blame/v1.0.1-alpha.153/packages/sql/tests/sql-query.spec.ts#L103
I discovered packages/sql isn't being tested.
> fix(sql): repair & enable @deepkit/sql tests

- packages/sql/src/sql-builder.ts
- packages/sql/src/sql-filter-builder.ts
- packages/sql/tests/sql-query.spec.ts
There are legitimate cases where a value may begin with `$`, and the current reference implementation breaks those cases.  Example case, I have a query that looks for duplicate products named `$100 Gift Card`.  This should result in: 
```
WHERE `products`.`name` = ?
```
but it instead translates into:
```
WHERE `products`.`name` = `products`.`100 GC`
```
This PR introduces a new `SqlReference` class that can be used for cases where a reference is actually desired.
I only see a single usage case in the Deepkit source, and it's in the tests.  It's unclear how many Deepkit users this may impact, but I do think it's important to fix.
> fix(sql): fix queries where value legitimately begins with $

- packages/type/src/serializer.ts
- packages/type/tests/issues/tuples.spec.ts
- When a tuple definition contained "duplicated" union types like [number|null, number|null], the jitted function couldln't be build as some variable like `oldErrors` were already declared. Probably one block per number|null
Added scope 
- [x ] I waive and relinquish all rights regarding this changes (including code, text, and images) to Deepkit UG (limited), Germany. This changes (including code, text, and images) are under MIT license without name attribution, copyright notice, and permission notice requirement.
> fix(type): add scope in setter code to prevent `variable already declared #603

- packages/type-compiler/src/compiler.ts
Exported enums seem to not generate `__Ω` annotations in their respective `.d.ts` files. This leads to `Symbol ___Ω not found in...` type errors when other packages want to use those definitions.
Adding this check *seems* to have the desired effect and looks like one of the other checks above: https://github.com/deepkit/deepkit-framework/blob/master/packages/type-compiler/src/compiler.ts#L910
> fix(type-compiler): include enum annotations in .d.ts transformation

- packages/mysql/src/mysql-adapter.ts
- packages/mysql/tests/mysql.spec.ts
MySQL deletes aren't checking for a modified row count. As a result, if you perform a delete that affects 0 rows, and the `@_pk` session variable is set from a previous operation on that MySQL connection, `delete` returns incorrect values for its `primaryKeys` and `modified` result object properties.
> fix(mysql): don't process delete PKs if no rows were affected

- packages/app/src/command.ts
- packages/core/src/types.ts
- packages/desktop-ui/src/components/app/state.ts
- packages/http/src/model.ts
- packages/http/src/module.ts
- packages/http/src/request-parser.ts
- packages/http/tests/router.spec.ts
- packages/injector/src/injector.ts
- packages/injector/src/types.ts
- packages/type-compiler/src/compiler.ts
- packages/type-compiler/tests/transpile.spec.ts
- packages/type/src/reflection/type.ts
- packages/type/src/validator.ts
- packages/type/tests/integration2.spec.ts
- packages/type/tests/issues/test.spec.ts
- packages/type/tests/issues/type-annotation.spec.ts
- packages/type/tests/performance-issue1.spec.ts
- packages/type/tests/serializer.spec.ts
- packages/type/tests/type.spec.ts
- packages/type/tsconfig.json
this makes TypeAnnotation not interfere with the type system at all. Previously we had all sorts of issues, especially with property inheritance and union grouping (type collapsing). This fixes now all of that
closes #626
> fix(type): convert TypeAnnotation into intrinsic type

- packages/postgres/tests/postgres.spec.ts
- packages/sql/src/sql-builder.ts
- packages/sqlite/tests/sqlite.spec.ts
Added functionality to filter database fields by custom names via `DatabaseField` metadata. Updated tests for SQLite and Postgres to validate the new feature and ensured proper aliasing in SQL queries using the `AS` keyword.
> feat(sql): support custom database field name filtering

- packages/http/src/model.ts
- packages/http/src/module.config.ts
- packages/http/src/request-parser.ts
- packages/http/tests/parser.spec.ts
- packages/http/tests/utils.ts
Formidable 3.0 deprecated the `multiples` option and changed the functionality of urlencoded & multipart parsing to always output arrays (https://github.com/node-formidable/formidable/pull/730).
This PR automatically pulls up the value from single-element arrays, while leaving multi-element arrays as arrays, which fixes input validation for HTTP payloads when using urlencoded & multipart values (other payloads are unaffected).
Also adds an HttpParserConfig config (off by default) for enabling the extraction of JSON payloads alongside file uploads in multipart submissions:
```
const fd = new FormData();
fd.add('file', myFileInput.files[0]);
fd.add('json', '{"my": "other", "json": "payload"}');
```
Added multi-part parsing test, including single value, multi-value, JSON payload, and files. …
> fix(http): proper handling of encoded & multipart values, plus multipart JSON support

- packages/type-compiler/src/compiler.ts
- packages/type/tests/compiler.spec.ts
* fix(type-compiler): generate optional metadata for method signatures and method declarations #647 
> fix(type-compiler) emit optional metadata for methods

- packages/orm/src/plugin/soft-delete-plugin.ts
the functions of the soft-delete plugin `restoreOne()`, `restoreMany()`, `hardDeleteOne()` & `hardDeleteMany()` are using the query functions `patchOne()`, `patchMany()`, `deleteOne()` & `deleteMany()` under the hood. We should probably return the result of those operations as well so they are consistent and can be used identically to the underlying query functions.
> fix(orm): return soft delete query results to be consistent with normal query operation results
