- README.md
Correction of a small typo in the README.md file.
> Small typo in the README.md

- DEVELOPMENT.md
- README.md
- Updates README.md with status, link to docs and a unique description for the @deepkit/http package
- Adds a DEVELOPMENT.md doc with notes on how to get started working on the Deepkit codebase
> docs: update readme and add development notes

- README.md
- Updates broken link in readme so that users can view the example app
> fix(docs): link to example app

- packages/bson/src/bson-serialize.ts
> Fix bigint prototype being modified, fixes #162

- packages/http/src/http.ts
> feat(http): add more http errors

- packages/api-console-gui/src/app/views/http/route-detail.component.ts
> fix(framework-debug-gui): fix request headers

- packages/type-compiler/src/resolver.ts
TSC allows users to configure module resolution by implementing
host.resolveModuleNames. This is used both by Deno and ChiselStrike.
Unfortunately, I couldn't find an exported TSC function that uses
host.resolveModuleNames or the builtin resolution, so I implemented
the logic in the type-compiler.
> Use host.resolveModuleNames when available

- packages/type-compiler/src/compiler.ts
Refs: #332
Supports tsconfig.json extends
(Nx monorepo)
> feat: Compiler handle tsConfig extends

- packages/http/src/decorator.ts
- packages/http/tests/decorator.spec.ts
- packages/http/tests/router.spec.ts
> feat(http): make action groups ordered

- DEVELOPMENT.md
As discussed in #399 a few additions to DEVELOPMENT.md.
The section 'Using deepkit-framework checkout with own project' is stolen from discord ;-)
Remarks:
- I have Python3 and it works - Python2 seems not needed?
- I don't know when and why tsc-watch:esm is needed
> improve DEVELOPMENT.md

- packages/type-compiler/src/compiler.ts
- packages/type/tests/compiler.spec.ts
> feat(type-compiler): emit typeName for type only imports

- README.md
> chore: update community package links for graphql

- package-lock.json
- packages/broker/package.json
- packages/broker/src/adapters/deepkit-adapter.ts
- packages/broker/src/broker.ts
- packages/broker/src/kernel.ts
- packages/broker/src/model.ts
- packages/broker/src/snapshot.ts
- packages/broker/src/utils.ts
- packages/broker/tests/broker.spec.ts
- packages/broker/tests/snapshot.spec.ts
- packages/framework-integration/package.json
- packages/framework/package.json
> feat(broker): queue message deduplication

- packages/framework/src/rpc.ts
- packages/rpc/src/server/action.ts
- packages/rpc/src/server/kernel.ts
- packages/rpc/src/server/security.ts
- packages/rpc/tests/security.spec.ts
> feat(rpc): make kernel connection available in kernel security

- packages/injector/src/module.ts
- packages/injector/tests/injector.spec.ts
> feat(injector): throw error when both forRoot and exports are used in module

- packages/type-compiler/src/config.ts
- packages/type-compiler/src/resolver.ts
- packages/type-compiler/tests/config.spec.ts
> fix(type-compiler): pattern match exclusion for globs

- .editorconfig
- .prettierignore
- .prettierrc
> chore: update prettier & editor configs

- website/src/pages/documentation/runtime-types/getting-started.md
Fixed reflection example
Replaces https://github.com/deepkit/deepkit-framework/pull/559
> fix(website): modify broken reflection example

- DEVELOPMENT.md
- docs/setup-env-ubundu.md
Add step by step guide for how to setup requirements on an ubuntun machine
- [x ] I waive and relinquish all rights regarding this changes (including code, text, and images) to Deepkit UG (limited), Germany. This changes (including code, text, and images) are under MIT license without name attribution, copyright notice, and permission notice requirement.
> docs: add how to setup dev env in ubuntu

- website/src/pages/documentation/framework.md
> docs: fix a typo

- README.md
> chore: add deepkit angular to examples

- packages/rpc/src/events.ts
- packages/rpc/src/server/action.ts
- packages/rpc/src/server/kernel.ts
> fix(rpc): missing .js extension on imports
